import {parseHTML} from 'linkedom';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('card.html','utf8');
new vm.Script(html.match(/<script>([\s\S]*)<\/script>/)[1]);
const {document}=parseHTML(fs.readFileSync('template.html','utf8'));
let app,calls=[];
class App {constructor(){app=this} async connect(){} async openLink(input){calls.push(input)} async callServerTool(){throw Error('No polling allowed')}}
const source=fs.readFileSync('app.js','utf8').replace(/^import[^\n]*\n/,'');
vm.runInNewContext(source,{document,App,applyDocumentTheme(){},console});
assert.equal(document.getElementById('visual').hidden,true,'no setup or placeholder UI');
assert.equal(document.querySelector('header'),null);
assert.equal(document.querySelector('h1'),null);
let media={object_id:'frame',url:'https://media.test/frame.png',caption:'<img src=x onerror=alert(1)>',media_type:'image/png'};
app.ontoolresult({structuredContent:{media}});
assert.equal(document.querySelectorAll('img').length,1);
assert.equal(document.querySelector('img').alt,media.caption);
assert.equal(document.getElementById('download').hidden,true);
media={object_id:'final',url:'https://media.test/video.mp4?ticket=x',download_url:'https://media.test/video.mp4?ticket=x&download=true',media_type:'video/mp4'};
app.ontoolresult({structuredContent:{media}});
const video=document.querySelector('video');assert(video);assert.equal(video.controls,true);
app.ontoolresult({structuredContent:{media}});assert.equal(document.querySelector('video'),video,'do not reset playback');
assert.equal(document.getElementById('download').hidden,false);
await document.getElementById('download').onclick();assert.equal(calls[0].url,media.download_url);
assert.equal(calls.length,1,'no background tool calls');
await app.onteardown();console.log('PASS media-only view no placeholders no polling image video download and stable playback');
